pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "base=master"
      - "#approved-reviews-by>=1"
      - "check-success=Build"
      - "label=mergify/can-merge"
      - "label!=Waiting other PRs"
    actions:
      merge:
        method: squash